[package]
name = "folder_check"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.4"
clap = { version = "4.3.0", features = ["derive"] }
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
aws-sdk-s3 = "1.56.0"
aws-config = "1.5.8"
tokio = { version = "1.0", features = ["full"] }